{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Q1 of 5**\n",
    "What will be the output of the below program?\n",
    "\n",
    "```java\n",
    "What will be the output of the below program?\n",
    "\n",
    "class ParentClass extends Exception {\n",
    "};\n",
    "\n",
    "class ChildClass extends ParentClass {\n",
    "};\n",
    "\n",
    "public class Tester {\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tthrow new ChildClass();\n",
    "\t\t} catch (ParentClass p) {\n",
    "\t\t\tSystem.out.println(\"Caught ParentClass exception\");\n",
    "\t\t} catch (ChildClass e) {\n",
    "\t\t\tSystem.out.println(\"Caught ChildClass exception\");\n",
    "\t\t}\n",
    "\t}\n",
    "}\n",
    "```\n",
    "- Caught Parent Class Exception []\n",
    "- Caught Child Class Exception []\n",
    "- Compilation error because the ChildClass is not throwable []\n",
    "- Compilation error because the catch block of a parent class exception must appear after the catch block of a child class exception [x]\n",
    "\n",
    "Explanation :\n",
    "The catch block of a parent class exception must appear after the catch block of a child class exception. If the catch block of a parent class exception appears before, then there will be a compilation error.\n",
    "\n",
    "**Q2 of 5**\n",
    " \n",
    " ```java\n",
    " class Tester {\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\t// Insert code here\n",
    "\t\t} catch (RuntimeException e) {\n",
    "\t\t}\n",
    "\t}\n",
    "}\n",
    "```\n",
    "Which of the following statements could be inserted at the comment (// Insert code here) to allow the above code to compile and run?\n",
    "\n",
    "- throw new ArrayIndexOutOfBoundsException(); [x]\n",
    "- throw new Exception(); []\n",
    "- throw new NullPointerException(); [x] \n",
    "- throw new IOException(); []\n",
    "\n",
    "Explanation :\n",
    "ArrayIndexOutOfBoundsException is a child of RuntimeException class and can be caught by RuntimeException class.\n",
    "\n",
    "Explanation :\n",
    "NullPointerException is a child of RuntimeException class and can be caught by RuntimeException class.\n",
    "\n",
    "**Q3 of 5**\n",
    "\n",
    "What will be the output of the below program?\n",
    "\n",
    "```java\n",
    "public class Tester {\n",
    "\n",
    "\tpublic static void display() {\n",
    "\t\tSystem.out.print(\" inside display()\");\n",
    "\t\tthrow new RuntimeException();\n",
    "\t}\n",
    "\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tSystem.out.print(\"main\");\n",
    "\t\t\tdisplay();\n",
    "\t\t} catch (Exception e) {\n",
    "\t\t\tSystem.out.print(\" caught\");\n",
    "\t\t} finally {\n",
    "\t\t\tSystem.out.print(\" finally\");\n",
    "\t\t}\n",
    "\t\tSystem.out.print(\" end\");\n",
    "\t}\n",
    "}\n",
    "```\n",
    "- Compilation error as 'throws' keyword is not used []\n",
    "- main inside display() caught end []\n",
    "- main inside display() caught finally end [x] \n",
    "- Runtime exception []\n",
    "\n",
    "Explanation :\n",
    "First, the main() method is executed, then, the display() method is invoked and executed which throws an exception. The exception gets handled in the catch block and then, the finally block gets executed. At last, end is displayed.\n",
    "\n",
    "**Q4 of 5**\n",
    "\n",
    "What will be the output of the below program?\n",
    "\n",
    "```java\n",
    "public class Tester {\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tmethod1();\n",
    "\t\t\tSystem.out.print(\"A\");\n",
    "\t\t} catch (Exception e) {\n",
    "\t\t\tSystem.out.print(\"B\");\n",
    "\t\t} catch (Throwable e) {\n",
    "\t\t\tSystem.out.print(\"C\");\n",
    "\t\t} finally {\n",
    "\t\t\tSystem.out.print(\"D\");\n",
    "\t\t}\n",
    "\t\tSystem.out.println(\"E\");\n",
    "\t}\n",
    "\n",
    "\tpublic static void method1() {\n",
    "\t\tthrow new Error();\n",
    "\t}\n",
    "}\n",
    "```\n",
    "\n",
    "- ABDE []\n",
    "- BDE []\n",
    "- ABCDE []\n",
    "- CDE [x]\n",
    "\n",
    "Explanation :\n",
    "Since, Error class is a child class of Throwable class, the corresponding catch block of Throwable will handle the exception and C is displayed. Then, finally block is executed and after that E is displayed.\n",
    "\n",
    "**Q5 of 5**\n",
    "\n",
    "What will be the output of the below program?\n",
    "\n",
    "```java\n",
    "interface A {\n",
    "\tvoid eval(int x);\n",
    "}\n",
    "\n",
    "class B implements A {\n",
    "\tpublic void eval(int x) {\n",
    "\t\tif (x == 0)\n",
    "\t\t\tthrow new RuntimeException();\n",
    "\t\tSystem.out.println(\"Evaluating...\");\n",
    "\t}\n",
    "}\n",
    "\n",
    "public class ExceptionDemo {\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\tB obj = new B();\n",
    "\t\tobj.eval(0);\n",
    "\t}\n",
    "}\n",
    "```\n",
    "- An exception of type RuntimeException will be thrown. [x]\n",
    "- Compilation error because overridden method eval() cannot throw an exception []\n",
    "- Compilation error because there is no throws declaration in eval() method in B []\n",
    "- Compilation error because the abstract method in A doesn't declare exception to be thrown []\n",
    "\n",
    "Explanation :\n",
    "RuntimeException will be thrown."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
